/* Use this script if you need to support IE 7 and IE 6. */

window.onload = function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'icomoon\'">' + entity + '</span>' + html;
	}
	var icons = {
			'icon-youtube' : '&#x21;',
			'icon-file-zip' : '&#x22;',
			'icon-file-xml' : '&#x23;',
			'icon-file-css' : '&#x24;',
			'icon-share' : '&#x25;',
			'icon-tags' : '&#x26;',
			'icon-printer' : '&#x27;',
			'icon-atom' : '&#x28;',
			'icon-globe' : '&#x29;',
			'icon-ying-yang' : '&#x2a;',
			'icon-stop' : '&#x2b;',
			'icon-blocked' : '&#x2c;',
			'icon-book' : '&#x2d;',
			'icon-cloudy' : '&#x2e;',
			'icon-moon' : '&#x2f;',
			'icon-sun' : '&#x30;',
			'icon-envelope' : '&#x31;',
			'icon-music' : '&#x32;',
			'icon-male' : '&#x33;',
			'icon-female' : '&#x34;',
			'icon-info' : '&#x35;',
			'icon-bookmark' : '&#x36;',
			'icon-retweet' : '&#x37;',
			'icon-abacus' : '&#x38;',
			'icon-attachment' : '&#x39;',
			'icon-pencil' : '&#x3a;',
			'icon-scissors' : '&#x3b;',
			'icon-profile' : '&#x3c;',
			'icon-volume' : '&#x3d;',
			'icon-resize' : '&#x3e;',
			'icon-resize-2' : '&#x3f;',
			'icon-list' : '&#x40;',
			'icon-grid' : '&#x41;',
			'icon-list-2' : '&#x42;',
			'icon-grid-2' : '&#x43;',
			'icon-tools' : '&#x44;',
			'icon-brush' : '&#x45;',
			'icon-chat' : '&#x46;',
			'icon-megaphone' : '&#x47;',
			'icon-pil' : '&#x48;',
			'icon-injection' : '&#x49;',
			'icon-thermometer' : '&#x4a;',
			'icon-lamp' : '&#x4b;',
			'icon-david-star' : '&#x4c;',
			'icon-cross' : '&#x4d;',
			'icon-moon-and-star' : '&#x4e;',
			'icon-magnifier' : '&#x4f;',
			'icon-stack' : '&#x50;',
			'icon-hand' : '&#x51;',
			'icon-folder' : '&#x52;',
			'icon-alarm' : '&#x53;',
			'icon-phone' : '&#x54;',
			'icon-lab' : '&#x55;',
			'icon-location' : '&#x56;',
			'icon-download' : '&#x57;',
			'icon-chart' : '&#x58;',
			'icon-chart-2' : '&#x59;',
			'icon-upload' : '&#x5a;',
			'icon-cloud' : '&#x5b;',
			'icon-eye' : '&#x5c;',
			'icon-pictures' : '&#x5d;',
			'icon-picture' : '&#x5e;',
			'icon-pacman' : '&#x5f;',
			'icon-time' : '&#x60;',
			'icon-headphones' : '&#x61;',
			'icon-link' : '&#x62;',
			'icon-warning' : '&#x63;',
			'icon-cog' : '&#x64;',
			'icon-cogs' : '&#x65;',
			'icon-cog-2' : '&#x66;',
			'icon-ipod' : '&#x67;',
			'icon-monitor' : '&#x68;',
			'icon-coffee' : '&#x69;',
			'icon-window' : '&#x6a;',
			'icon-microphone' : '&#x6b;',
			'icon-file' : '&#x6c;',
			'icon-phone-2' : '&#x6d;',
			'icon-tablet' : '&#x6e;',
			'icon-camera' : '&#x6f;',
			'icon-film' : '&#x70;',
			'icon-calendar' : '&#x71;',
			'icon-safari' : '&#x72;',
			'icon-opera' : '&#x73;',
			'icon-IE' : '&#x74;',
			'icon-firefox' : '&#x75;',
			'icon-chrome' : '&#x76;',
			'icon-css3' : '&#x77;',
			'icon-html5' : '&#x78;',
			'icon-paypal' : '&#x79;',
			'icon-file-openoffice' : '&#x7a;',
			'icon-file-pdf' : '&#x7b;',
			'icon-file-word' : '&#x7c;',
			'icon-file-excel' : '&#x7d;',
			'icon-file-powerpoint' : '&#x7e;',
			'icon-android' : '&#xe000;',
			'icon-windows' : '&#xe001;',
			'icon-tux' : '&#xe002;',
			'icon-apple' : '&#xe003;',
			'icon-github' : '&#xe004;',
			'icon-wordpress' : '&#xe005;',
			'icon-blogger' : '&#xe006;',
			'icon-picassa' : '&#xe007;',
			'icon-flickr' : '&#xe008;',
			'icon-vimeo' : '&#xe009;',
			'icon-feed' : '&#xe00a;',
			'icon-twitter' : '&#xe00b;',
			'icon-share-2' : '&#xe00c;',
			'icon-code' : '&#xe00d;',
			'icon-facebook' : '&#xe00e;',
			'icon-google-plus' : '&#xe00f;',
			'icon-paragraph-left' : '&#xe010;',
			'icon-paragraph-center' : '&#xe011;',
			'icon-paragraph-right' : '&#xe012;',
			'icon-paragraph-justify' : '&#xe013;',
			'icon-menu' : '&#xe014;',
			'icon-arrow-left' : '&#xe015;',
			'icon-arrow-down' : '&#xe016;',
			'icon-arrow-right' : '&#xe017;',
			'icon-arrow-up' : '&#xe018;',
			'icon-thumbs-up' : '&#xe019;',
			'icon-thumbs-down' : '&#xe01a;',
			'icon-cancel' : '&#xe01b;',
			'icon-checkmark' : '&#xe01c;',
			'icon-minus' : '&#xe01d;',
			'icon-plus' : '&#xe01e;',
			'icon-target' : '&#xe01f;',
			'icon-home' : '&#xe020;',
			'icon-volume-2' : '&#xe021;'
		},
		els = document.getElementsByTagName('*'),
		i, attr, html, c, el;
	for (i = 0; i < els.length; i += 1) {
		el = els[i];
		attr = el.getAttribute('data-icon');
		if (attr) {
			addIcon(el, attr);
		}
		c = el.className;
		c = c.match(/icon-[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
};